In [2]:
pip install pandas

Collecting pandas
  Downloading pandas-2.2.3-cp310-cp310-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.22.4 in d:\coading\python\venv\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\coading\python\venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in d:\coading\python\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading pandas-2.2.3-cp310-cp310-win_amd64.whl (11.6 MB)
   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.6 MB 5.6 MB/s eta 0:00:02
   --- ------------------------------------ 1.0/11.6 MB 3.0 MB/s eta 0:00:04
   --- ------------------------------------ 1.0/11.6 MB 3.0 MB/s eta 0:00:04
   ------ --------------------------------- 1.8/11.6 MB 2.1 MB/s eta 0:00:05
   -------- ------------------------------- 2.4/11.6 MB 2.3 MB/s eta 0:00:04
   --------- ------------------------------ 2.9/11.6 MB 2.4 MB/s eta 0:00:04
   ------------ --------------------------- 3.7/11.6 MB 2.5 MB/s eta 0:00:04
   --------------- ------------------------ 4.5/11.6 MB 2.7 MB/s eta 0:00:03
   ------------------ --------------------- 5.2/11.6 MB 2.8 MB/s eta 0:00:03
   -------------------- ------------------- 6.0/11.6 MB 3.0 MB/s eta 0:00:02
   ----------------------- ---------------- 6.8/11.6 MB 3.0 MB/s eta 0:00:02
   -------------------------- ------------- 7.6/11.6 MB 3.0 MB/s eta 0:00:02
   ---------------------------- ----------- 8.4/11.6 MB 3.1 MB/s eta 0:00:02
   -------------------------------- ------- 9.4/11.6 MB 3.2 MB/s eta 0:00:01
   ------------------------------------- -- 10.7/11.6 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------- 11.6/11.6 MB 3.5 MB/s eta 0:00:00
Downloading pytz-2024.2-py2.py3-none-any.whl (508 kB)
Downloading tzdata-2024.2-py2.py3-none-any.whl (346 kB)
Installing collected packages: pytz, tzdata, pandas
Successfully installed pandas-2.2.3 pytz-2024.2 tzdata-2024.2
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [4]:
#Series- Array Like 1D structure
data=[1,2,3,4,5]
series=pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
#Series using Dictionary
data ={'a':1 , 'b': 2, 'c':3}
series=pd.Series(data)
print(data)

{'a': 1, 'b': 2, 'c': 3}

In [6]:
data=[10,20,30]
index=[1,2,3]
series=pd.Series(data,index=index)
print(series)

1    10
2    20
3    30
dtype: int64

In [3]:
#DataFrame

data={
    'Name':['Psa','May','Shr'],
    'Age': [19,20,20]
}
df=pd.DataFrame(data)
print(df)

  Name  Age
0  Psa   19
1  May   20
2  Shr   20

In [4]:
df

  Name  Age
0  Psa   19
1  May   20
2  Shr   20

In [5]:
df['Salary']=[50000,60000,70000]
df

  Name  Age  Salary
0  Psa   19   50000
1  May   20   60000
2  Shr   20   70000

In [7]:
df=pd.read_csv('main.csv')

In [8]:
df.head(5)

,nick,country,stats_link,teams,maps_played,rounds_played,kd_difference,kd_ratio,rating,total_kills,headshot_percentage,total_deaths,grenade_damage_per_round,kills_per_round,assists_per_round,deaths_per_round,teammate_saved_per_round,saved_by_teammate_per_round,kast,impact
0,ZywOo,France,https://www.hltv.org//stats/players/11893/zywoo,"['Vitality', 'aAa']",970,25491,5917,1.38,1.27,21602,41.3,15685,3.6,0.85,0.13,0.62,0.10,0.12,74.9,1.45
1,s1mple,Ukraine,https://www.hltv.org//stats/players/7998/s1mple,['Natus Vincere'],1532,40464,8864,1.34,1.25,34647,41.3,25783,2.4,0.86,0.10,0.64,0.08,0.11,74.2,1.36
2,sh1ro,Russia,https://www.hltv.org//stats/players/16920/sh1ro,"['Gambit Youngsters', 'Gambit']",847,22465,5361,1.45,1.23,17320,27.9,11959,3.9,0.77,0.11,0.53,0.08,0.11,76.3,1.21
3,deko,Russia,https://www.hltv.org//stats/players/20113/deko,['1WIN'],378,10219,2225,1.37,1.22,8219,36.9,5994,3.3,0.80,0.10,0.59,0.09,0.11,74.5,1.21
4,Kaze,Malaysia,https://www.hltv.org//stats/players/8950/kaze,"['ViCi', 'Flash', 'MVP.karnal']",829,21617,4118,1.32,1.20,16957,30.3,12839,2.9,0.78,0.11,0.59,0.08,0.10,73.7,1.24

In [9]:
df.tail(5)

,nick,country,stats_link,teams,maps_played,rounds_played,kd_difference,kd_ratio,rating,total_kills,headshot_percentage,total_deaths,grenade_damage_per_round,kills_per_round,assists_per_round,deaths_per_round,teammate_saved_per_round,saved_by_teammate_per_round,kast,impact
798,B1ad3,Ukraine,https://www.hltv.org//stats/players/472/b1ad3,['FlipSid3'],899,23232,-3408,0.80,0.83,13472,41.9,16880,2.6,0.58,0.16,0.73,0.10,0.07,64.6,0.84
799,netrick,Denmark,https://www.hltv.org//stats/players/8422/netrick,"['AGF', 'unknown', 'LPSP', 'Forcebuy']",455,11976,-1736,0.80,0.82,6753,48.2,8489,6.6,0.56,0.14,0.71,0.11,0.09,66.3,0.85
800,HUNDEN,Denmark,https://www.hltv.org//stats/players/7415/hunden,"['Tricked', 'ALTERNATE aTTaX']",1578,41153,-6238,0.78,0.81,22470,48.7,28708,4.5,0.55,0.14,0.70,0.11,0.09,66.8,0.80
801,RuFire,Russia,https://www.hltv.org//stats/players/13156/rufire,"['SG.pro', '5balls', 'VP.Prodigy']",384,10185,-1927,0.74,0.78,5579,47.9,7506,4.7,0.55,0.14,0.74,0.09,0.06,63.3,0.81
802,OCEAN,Canada,https://www.hltv.org//stats/players/6455/ocean,"['subtLe', 'SKDC', 'Splyce']",410,10602,-1962,0.74,0.77,5530,44.3,7492,3.6,0.52,0.12,0.71,0.09,0.08,64.3,0.72

In [10]:
df.describe()

,maps_played,rounds_played,kd_difference,kd_ratio,rating,total_kills,headshot_percentage,total_deaths,grenade_damage_per_round,kills_per_round,assists_per_round,deaths_per_round,teammate_saved_per_round,saved_by_teammate_per_round,kast,impact
count,803.000000,803.000000,803.000000,803.000000,803.00000,803.000000,803.000000,803.000000,803.000000,803.000000,803.000000,803.000000,803.000000,803.000000,803.000000,803.000000
mean,833.174346,21893.596513,585.465753,1.035430,1.01188,15142.087173,45.462017,14556.518057,4.061395,0.688904,0.131046,0.666949,0.096015,0.096862,70.112827,1.054944
std,402.388811,10607.751477,1475.806605,0.092114,0.06656,7539.729631,8.416641,7018.031710,1.187467,0.044705,0.017702,0.030042,0.011236,0.013084,1.790944,0.100154
min,374.000000,9498.000000,-6238.000000,0.740000,0.77000,5530.000000,23.600000,5994.000000,1.400000,0.520000,0.080000,0.530000,0.040000,0.060000,63.300000,0.700000
25%,500.500000,13227.000000,-283.000000,0.980000,0.97000,9092.500000,40.500000,8842.500000,3.200000,0.660000,0.120000,0.650000,0.090000,0.090000,69.000000,0.990000
50%,734.000000,19174.000000,358.000000,1.030000,1.01000,13132.000000,47.300000,12603.000000,3.900000,0.690000,0.130000,0.670000,0.100000,0.100000,70.100000,1.060000
75%,1059.000000,27881.000000,1313.500000,1.090000,1.05000,19214.000000,51.450000,18226.500000,4.800000,0.720000,0.140000,0.690000,0.100000,0.110000,71.400000,1.120000
max,2169.000000,56914.000000,8864.000000,1.450000,1.27000,40884.000000,68.400000,38351.000000,9.100000,0.860000,0.180000,0.750000,0.140000,0.160000,76.300000,1.450000

In [11]:
df.dtypes

nick                            object
country                         object
stats_link                      object
teams                           object
maps_played                      int64
rounds_played                    int64
kd_difference                    int64
kd_ratio                       float64
rating                         float64
total_kills                      int64
headshot_percentage            float64
total_deaths                     int64
grenade_damage_per_round       float64
kills_per_round                float64
assists_per_round              float64
deaths_per_round               float64
teammate_saved_per_round       float64
saved_by_teammate_per_round    float64
kast                           float64
impact                         float64
dtype: object

In [12]:
df.isnull()

,nick,country,stats_link,teams,maps_played,rounds_played,kd_difference,kd_ratio,rating,total_kills,headshot_percentage,total_deaths,grenade_damage_per_round,kills_per_round,assists_per_round,deaths_per_round,teammate_saved_per_round,saved_by_teammate_per_round,kast,impact
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
798,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
799,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
800,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
801,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
802,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [13]:
df.isnull().sum()

nick                           0
country                        0
stats_link                     0
teams                          0
maps_played                    0
rounds_played                  0
kd_difference                  0
kd_ratio                       0
rating                         0
total_kills                    0
headshot_percentage            0
total_deaths                   0
grenade_damage_per_round       0
kills_per_round                0
assists_per_round              0
deaths_per_round               0
teammate_saved_per_round       0
saved_by_teammate_per_round    0
kast                           0
impact                         0
dtype: int64